### ISSUE TITLE
Feature Bedrock Support

### ISSUE THREAD

**Issue by tedztar** [Cryptkeeper/mc-ping-updated#6]
It would be really cool if we could get bedrock support

**Comment by DevBonBon** [comment]
After a quick look at the bedrock [docs](https://wiki.vg/Pocket_Edition_Protocol_Documentation), there doesn't seem to be anything similar to what the java edition has. It does support basic ping packets, but as the format is so different, it should be implemented in its own package

**Comment by Cryptkeeper** [comment]
For Bedrock support I recommend https://github.com/Falkirks/mcpe-ping for NodeJS and https://github.com/ZeroErrors/go-bedrockping for Golang.
